name: 'Eco CI Activity Checker'
description: 'check if there has been a commit in the specificed repo/branch since the last workflow run and write to github output'
inputs:
  repo:
    description: 'format: {repo-owner}/{repo-name}'
    required: true
  branch:
    description: 'the branch to check'
    required: true
  workflow-id:
    description: 'the id of the workflow'
    required: true
outputs:
  should_run:
    description: 
    value: ${{ steps.check_if_needs_to_run.outputs.should_run }}
runs:
  using: 'composite'
  steps:
    - id: check_if_needs_to_run
      name: check last workflow run and last commit
      shell: bash
      run: |
        api_response=$(curl -s https://api.github.com/repos/${{ inputs.repo }}/actions/workflows/${{ inputs.workflow-id }}/runs)
        dateoflastrun=$(echo $api_response | jq -r '.["workflow_runs"][1]["run_started_at"]')
        state=$(echo $api_response | jq -r '.["workflow_runs"][1]["conclusion"]')
        dateoflastcommit=$(curl -s https://api.github.com/repos/${{ inputs.repo }}/commits/${{ inputs.branch }} | jq -r '.commit.author.date')
        
        echo "last commit: $dateoflastcommit"
        echo "last run: $dateoflastrun"
        echo "state of last run: $state"
        
        if [ -z $dateoflastrun ] || [ -z $dateoflastcommit ];
        then
        echo "should_run=true" >> $GITHUB_OUTPUT\
        &&  echo "NULL returned in API call for Activity Checker" >> $GITHUB_STEP_SUMMARY;
        elif [ $state != 'success' ]; then echo "should_run=true" >> $GITHUB_OUTPUT;
        else
        lastrun_timestamp=$(date --date "$dateoflastrun" +'%s')
        commit_timestamp=$(date --date "$dateoflastcommit" +'%s')
        if [ $commit_timestamp -gt $lastrun_timestamp ]; then echo "should_run=true" >> $GITHUB_OUTPUT; fi
        if [ $commit_timestamp -lt $lastrun_timestamp ]; then echo "should_run=false" >> $GITHUB_OUTPUT && echo "Workflow on ${{ inputs.repo }} and branch ${{ inputs.branch }} had no recent commits." >> $GITHUB_STEP_SUMMARY; fi
        fi
