name: 'Eco CI Activity Checker'
description: 'check if there has been a commit in the specificed repo/branch within the specified time period and write to github output'
inputs:
  repo:
    description: 'format: {repo-owner}/{repo-name}'
    required: true
  branch:
    description: 'the branch to check'
    required: true
  workflow-id:
    description: 'the id of the workflow. if this is passed, it will also check if this has been run in the <time period>'
    required: true
outputs:
  should_run:
    description: 
    value: ${{ steps.check_if_needs_to_run.outputs.should_run }}
runs:
  using: 'composite'
  steps:
    - id: check_if_needs_to_run
      name: check last workflow run and last commit
      shell: bash
      run: |
        if [ -z $dateoflastrun ] || [ -z $dateoflastcommit ];
        then
        echo "should_run=true" >> $GITHUB_OUTPUT\
        &&  echo "NULL returned in API call for Activity Checker" >> $GITHUB_STEP_SUMMARY;
        elif [ $state != 'success' ]; then echo "should_run=true" >> $GITHUB_OUTPUT;
        else
        lastrun_timestamp=$(date --date "$dateoflastrun" +'%s')
        commit_timestamp=$(date --date "$dateofcommit" +'%s')
        if [ $commit_timestamp -gt $lastrun_timestamp ]; then echo "should_run=true" >> $GITHUB_OUTPUT; fi
        if [ $commit_timestamp -lt $lastrun_timestamp ]; then echo "should_run=false" >> $GITHUB_OUTPUT && echo "Workflow skipped as there were no commits since the last successful workflow run." >> $GITHUB_STEP_SUMMARY; fi
        fi